# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
url: https://xuehongyanl.github.io
baseurl: /
title: Mr. L's Blog
description: Xue Hongyan's Blog | 薛泓彦的博客

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /blog/about.html

paths:
  base: /blog
  home: /
  all:  /blog/all.html
  rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: xuehongyanL/xuehongyanl.github.io
repository_tree: master

## Language & timezone ##
lang: zh #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai

## Author & social ##
author:
  name: "Xue Hongyan"
  email: shandianshu@foxmail.com
  # facebook:  #your Facebook username
  twitter: xuehongyan
  github:  xuehongyanL
  googleplus:
  weibo: 1738837907
  douban:
  # linkedin:  #your Linkedin username

## Comment system (Disqus) ##
disqus:
  shortname: xuehongyanl-github-io #the Disqus shortname for the site


## Google Analytics ##
ga_tracking_id: UA-71907556-1 #Google analytics id for the site

# mathjax: true

## Paginate ##
paginate: 7
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"
port: 4001

## Development ##
isdebug: false